server:
  port: 8080
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true